/**
 * setup.js
 *
 * Interactive configuration wizard for clwclw-monitor agent.
 * Writes settings to ~/.clwclw/.env
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { ensureHome } = require('./config');

function createInterface() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(rl, question, defaultValue) {
  const suffix = defaultValue ? ` [${defaultValue}]` : '';
  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      const val = answer.trim();
      resolve(val || defaultValue || '');
    });
  });
}

function askYesNo(rl, question, defaultYes) {
  const hint = defaultYes ? '[Y/n]' : '[y/N]';
  return new Promise((resolve) => {
    rl.question(`${question} ${hint}: `, (answer) => {
      const val = answer.trim().toLowerCase();
      if (!val) return resolve(defaultYes);
      resolve(val === 'y' || val === 'yes');
    });
  });
}

async function runSetup() {
  const home = ensureHome();
  const envPath = path.join(home, '.env');

  console.log('clwclw-monitor setup wizard');
  console.log(`Config will be saved to: ${envPath}`);
  console.log('');

  const rl = createInterface();
  const env = {};

  try {
    // --- Core ---
    console.log('--- Coordinator ---');
    env.COORDINATOR_URL = await ask(rl, 'Coordinator URL', 'http://localhost:8080');
    env.COORDINATOR_AUTH_TOKEN = await ask(rl, 'Auth token (leave empty if none)', '');

    // --- Agent ---
    console.log('');
    console.log('--- Agent ---');
    env.AGENT_NAME = await ask(rl, 'Agent name', require('os').hostname());

    // --- Telegram ---
    console.log('');
    const wantTelegram = await askYesNo(rl, 'Configure Telegram notifications?', false);
    if (wantTelegram) {
      env.TELEGRAM_ENABLED = 'true';
      env.TELEGRAM_BOT_TOKEN = await ask(rl, 'Telegram Bot Token', '');
      env.TELEGRAM_CHAT_ID = await ask(rl, 'Telegram Chat ID', '');
    }

    // --- Email ---
    console.log('');
    const wantEmail = await askYesNo(rl, 'Configure Email notifications?', false);
    if (wantEmail) {
      env.EMAIL_ENABLED = 'true';
      env.SMTP_HOST = await ask(rl, 'SMTP host', '');
      env.SMTP_PORT = await ask(rl, 'SMTP port', '587');
      env.SMTP_SECURE = await ask(rl, 'SMTP secure (true/false)', 'false');
      env.SMTP_USER = await ask(rl, 'SMTP user', '');
      env.SMTP_PASS = await ask(rl, 'SMTP password', '');
      env.EMAIL_FROM = await ask(rl, 'From email', env.SMTP_USER);
      env.EMAIL_TO = await ask(rl, 'To email', '');
    }

    // --- LINE ---
    console.log('');
    const wantLine = await askYesNo(rl, 'Configure LINE notifications?', false);
    if (wantLine) {
      env.LINE_ENABLED = 'true';
      env.LINE_CHANNEL_ACCESS_TOKEN = await ask(rl, 'LINE Channel Access Token', '');
      env.LINE_CHANNEL_SECRET = await ask(rl, 'LINE Channel Secret', '');
      env.LINE_USER_ID = await ask(rl, 'LINE User ID', '');
    }

    // --- Hooks ---
    console.log('');
    const wantHooks = await askYesNo(rl, 'Install Claude Code hooks now?', true);

    rl.close();

    // Write .env
    const lines = [
      '# clwclw-monitor configuration',
      `# Generated by clwclw setup on ${new Date().toISOString()}`,
      '',
    ];

    for (const [key, value] of Object.entries(env)) {
      if (value === '' || value === undefined) continue;
      // Quote values containing spaces or special characters
      const needsQuote = /[\s#"']/.test(value);
      lines.push(needsQuote ? `${key}="${value}"` : `${key}=${value}`);
    }
    lines.push('');

    fs.writeFileSync(envPath, lines.join('\n'), 'utf8');
    console.log('');
    console.log(`Configuration saved to ${envPath}`);

    if (wantHooks) {
      console.log('');
      const { installHooks } = require('./hooks');
      await installHooks();
    }

    console.log('');
    console.log('Setup complete! Next steps:');
    console.log('  clwclw heartbeat              # Test connection');
    console.log('  clwclw work --channel <name> --tmux-target <target>');
  } catch (err) {
    rl.close();
    throw err;
  }
}

module.exports = { runSetup };
